### ISSUE TITLE
Dependency management

### ISSUE THREAD

**Issue by luziferius** [sporkwitch/autokey#1]
I went ahead and forged a new release (0.95.0) in the upstream repository.

- I fiddled a bit with the dependencies in the control file. (This will cause you merge conflicts, sorry about that!)

- _I think_, you added a bit too much to the build dependencies: 
https://github.com/sporkwitch/autokey/blob/7f18355ddcacdd2180959f4331e310d2421dbcad/debian/control#L6-L17
This is definitely correct for projects written in a compiled language, like C++, because the libraries need to be present during the binary linking step. But since this is a pure Python project, almost all dependencies are pure runtime dependencies.
I decoupled setup.py and the autokey package here (https://github.com/autokey/autokey/commit/4d77b507a76581cfef5a66a4333eeeb619a40f48), thus the runtime dependencies should not be needed during the package build. (Because no autokey code is executed, thus the imports are not run.)

- You are manually adjusting the dependencies in the `debian/control` file each time you push a new release. I found a nice option that completely obsoletes fiddling with the `Replaces` specification.
You can use `${binary:Version}` to refer to the exact version of the currently built package.
Thus you can just specify that e.g. autokey-common `Replaces: autokey-common (<< ${binary:Version})` and be done with it. If currently built version is X.Y.Z, then the package will automatically replace everything <X.Y.Z.

- You changed the versions in `Replaces: autokey (<<0.61.4-0~0)`. As far as I know, the split into three packages (-common, -qt, -gtk) occurred after 0.61.4, so those were originally meant to ensure that ancient package versions get replaced. Well, bumping it should not cause issues, because even autokey (<< 100.0.0) would also match those. Just there is no package called exactly `autokey` any more.
In the upstream repo, I added a replacement dependency to each package, causing each to replace their older versions: (This takes care of the bullet point above)
https://github.com/sporkwitch/autokey/blob/7dfc02c820c68c84c4879478cffa48b06478ec7a/debian/control#L28
https://github.com/sporkwitch/autokey/blob/7dfc02c820c68c84c4879478cffa48b06478ec7a/debian/control#L54
https://github.com/sporkwitch/autokey/blob/7dfc02c820c68c84c4879478cffa48b06478ec7a/debian/control#L77

**Comment by sporkwitch** [comment]
The launchpad build fails during the tests if I don't specify the deps. Will take a look through the rest when I have a chance, probably this weekend 
v / r
Robert Klebes
Mobile: 571-492-8639
https://keybase.io/sporkwitch
https://www.linkedin.com/in/klebes

**Comment by luziferius** [comment]
It works using the reduced dependency set when building locally, but if launchpad tests fail, thats a very acceptable reason to have them specified. Thus, I'll treat my first point as invalid.

Ah. And another small thing: Both autokey-qt and autokey-gtk now require autokey-common to be on the exact same version as the GUI package. This prevents mixing different versions, which probably breaks anyway.

Thank you for taking the time and maintaining the PPA.
